version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/flask.conf:/etc/nginx/conf.d/flask.template
    ports:
      - '8080:80'
    command: 'bash -c "cat /etc/nginx/conf.d/flask.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
  flask:
    image: tiangolo/uwsgi-nginx-flask:python3.8-alpine
    user: root
    working_dir: /home/flask/app
    environment:
      - STATIC_URL=/static
      - STATIC_PATH=/home/flask/app/static
      - FLASK_APP=app.py
    volumes:
      - ./app:/home/flask/app
    ports:
      - '3000:3000'
    command: 'flask run --port=3000 --host=0.0.0.0'
