version: "3.0"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/php.conf:/etc/nginx/conf.d/php.template
      - ./nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./src:/var/www/html
    ports:
      - '8080:80'
    command: 'bash -c "cat /etc/nginx/conf.d/php.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'      
    links:
        - php-fpm

  php-fpm:
    image: php:8.1-fpm
    volumes:
      - ./src:/var/www/html